[tox]
env_list = wagtail{70,73,74,80rc1}

[testenv]
package = wheel
wheel_build_env = .pkg
deps =
    pytest>=8.4.2
    pytest-django>=4.11.1
    django==5.2.*
    wagtail70: wagtail==7.0.*
    wagtail73: wagtail==7.3.*
    wagtail74: wagtail==7.4.*
    wagtail80rc1: wagtail==8.0rc1
pip_pre =
    wagtail80rc1: true
commands =
    pytest tests/ {posargs}
